// $ANTLR 2.7.4: "complex.g" -> "ComplexListParser.java"$

/**
* this code is generated by ANTLR from the 'mathematica.g'-file
* @author Bernd Gonska
* @version 1.0
*/
package discreteGroup.parser;

public interface ComplexListParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int OPEN_BRACE = 4;
	int COLLON = 5;
	int CLOSE_BRACE = 6;
	int PLUS = 7;
	int MINUS = 8;
	int INTEGER_THING = 9;
	int DOT = 10;
	int STAR = 11;
	int HAT = 12;
	int LITERAL_I = 13;
	int BACKS = 14;
	int SLASH = 15;
	int DDOT = 16;
	int ID = 17;
	int ID_LETTER = 18;
	int DIGIT = 19;
	int STRING = 20;
	int ESC = 21;
	int WS_ = 22;
}
