// $ANTLR 2.7.4: "complex.g" -> "ComplexListParser.java"$

/**
* this code is generated by ANTLR from the 'mathematica.g'-file
* @author Bernd Gonska
* @version 1.0
*/
package discreteGroup.parser;
import java.util.Vector;

import antlr.NoViableAltException;
import antlr.ParserSharedInputState;
import antlr.RecognitionException;
import antlr.Token;
import antlr.TokenBuffer;
import antlr.TokenStream;
import antlr.TokenStreamException;
import antlr.collections.impl.BitSet;
import charlesgunn.math.Complex;

public class ComplexListParser extends antlr.LLkParser       implements ComplexListParserTokenTypes
 {

/**
* was es tut
* 
*
*/
	// initialisierung und java variablen
	Vector dimensions= new Vector(); // (int)
	boolean firstDimCount=true;
	boolean failure=false;
	
	// depth ist die aktuelle Tiefe in der Unterliste (ganz unten ist es gleich der Dimension)
	// depth 0 : in der obersten Liste
	// depth max : in den Blaettern die hoffentlich nur complexe Zahlen enthalten
	// depth max ist dimenson-1

	public Vector getDim(Vector dimLength , Vector data){
		// rekursiv
		if (data==null) return null;// FehlerFall
		dimLength.add(new Integer(data.size()));
		try{
			Complex c=(Complex)data.get(0); // ist das naechste eine Complexe Zahl?
			return dimLength;				// dann: RekursionsEnde
		}
		catch(Exception e)
		{
		 //gehe davon aus das es ein Vector ist
		 return getDim(dimLength, (Vector)data.get(0));
		}
	}
	
	// dim=0 -> erste Tiefe
	// informatisch zaehlen
	public boolean checkSize(int dim, Vector dimLength, Vector data){
		// rekursiv
		if (data==null) return false;				// FehlerFall
		int len=data.size();						// Laenge des aktuellen Vectors
		if (dimLength.size()<=dim) return false;	// falsche Dimension
		if (len!=((Integer)dimLength.get(dim)).intValue())	return false; // falsche Laenge
		if (dim==dimLength.size()-1){	// RekursionsEnde:
			try{
				Complex c;
				for (int i=0;i<len;i++)
					c=(Complex)data.get(i);// Fehler falls keine Complexe Zahl
			}
			catch(Exception e){return false;}
			return true;
		}
		for(int i=0;i<len;i++){
			if (checkSize(dim+1,dimLength,(Vector)data.get(i))){}
			else return false;	// Fehler aus tieferer rekursion weitergeben 
		}
		return true; // alles ok gewesen
	}
	
	private boolean checkDim(Vector data){
		if (data==null) return false;
		Vector dims= new Vector();
		dims= getDim(dims,data);
		if (dims==null) return false;
		return checkSize(0,dims,data);
	}


	
	
/**
* konstructs a parser who can translate a
* mathematica-file to a corresponding 
* multidimensional Array of complex numbers
* @param    see superclass
* example: MathematicaParser p=
*	    new MathematicaParser(new MathematicaLexer(
*	     new FileReader(new File("file.m"))));
*/

protected ComplexListParser(TokenBuffer tokenBuf, int k) {
  super(tokenBuf,k);
  tokenNames = _tokenNames;
}

public ComplexListParser(TokenBuffer tokenBuf) {
  this(tokenBuf,2);
}

protected ComplexListParser(TokenStream lexer, int k) {
  super(lexer,k);
  tokenNames = _tokenNames;
}

public ComplexListParser(TokenStream lexer) {
  this(lexer,2);
}

public ComplexListParser(ParserSharedInputState state) {
  super(state,2);
  tokenNames = _tokenNames;
}

/**
* starts the parsing Process
* @param none 	sourcefile set by creating the object
* @returns Vector of Vector of..	 which holds the ComplexNumbers
*/
	public final Vector  start() throws RecognitionException, TokenStreamException {
		Vector data;
		
		data=new Vector();
		
		try {      // for error handling
			{
			switch ( LA(1)) {
			case OPEN_BRACE:
			{
				data=arrayThing(0);
				break;
			}
			case EOF:
			{
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			
				  	if (!checkDim(data)) data=null;
				
		}
		catch (RecognitionException ex) {
			reportError(ex);
			consume();
			consumeUntil(_tokenSet_0);
		}
		return data;
	}
	
	private final Vector  arrayThing(
		int depth 
	) throws RecognitionException, TokenStreamException {
		Vector innerData;
		
		
		Complex c=new Complex();
		innerData=new Vector();
		Vector nextArray=new Vector();
		int childCount=0;
		
		
		try {      // for error handling
			match(OPEN_BRACE);
			{
			switch ( LA(1)) {
			case PLUS:
			case MINUS:
			case INTEGER_THING:
			case DOT:
			case LITERAL_I:
			{
				c=complexThing();
				childCount++;	 innerData.add(c);	
				{
				_loop6:
				do {
					if ((LA(1)==COLLON)) {
						match(COLLON);
						c=complexThing();
						childCount++;	 innerData.add(c);	
					}
					else {
						break _loop6;
					}
					
				} while (true);
				}
				break;
			}
			case OPEN_BRACE:
			{
				nextArray=arrayThing(depth+1);
				childCount++;	 innerData.add(nextArray);	
				{
				_loop8:
				do {
					if ((LA(1)==COLLON)) {
						match(COLLON);
						nextArray=arrayThing(depth+1);
						childCount++;	 innerData.add(nextArray);	
					}
					else {
						break _loop8;
					}
					
				} while (true);
				}
				break;
			}
			case CLOSE_BRACE:
			{
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			match(CLOSE_BRACE);
		}
		catch (RecognitionException ex) {
			reportError(ex);
			consume();
			consumeUntil(_tokenSet_1);
		}
		return innerData;
	}
	
	private final Complex  complexThing() throws RecognitionException, TokenStreamException {
		Complex c;
		
		double temp1=0;
		double temp2=0;
		int sign=1;
		int sign2=1;
		double re=0;
		double im=0;
		c=new Complex();
		
		try {      // for error handling
			{
			if ((LA(1)==PLUS) && (_tokenSet_2.member(LA(2)))) {
				match(PLUS);
				sign=1;
			}
			else if ((LA(1)==MINUS) && (_tokenSet_2.member(LA(2)))) {
				match(MINUS);
				sign=-1;
			}
			else if ((_tokenSet_2.member(LA(1))) && (_tokenSet_3.member(LA(2)))) {
			}
			else {
				throw new NoViableAltException(LT(1), getFilename());
			}
			
			}
			{
			switch ( LA(1)) {
			case LITERAL_I:
			{
				match(LITERAL_I);
				re=0;im=sign*1;
				break;
			}
			case PLUS:
			case MINUS:
			case INTEGER_THING:
			case DOT:
			{
				temp1=doubleThing();
				re=sign*temp1; im=0;
				{
				if ((LA(1)==STAR||LA(1)==LITERAL_I) && (LA(2)==COLLON||LA(2)==CLOSE_BRACE||LA(2)==LITERAL_I)) {
					{
					switch ( LA(1)) {
					case STAR:
					{
						match(STAR);
						break;
					}
					case LITERAL_I:
					{
						break;
					}
					default:
					{
						throw new NoViableAltException(LT(1), getFilename());
					}
					}
					}
					match(LITERAL_I);
					re=0; im=sign*temp1;
				}
				else if ((_tokenSet_2.member(LA(1))) && (_tokenSet_3.member(LA(2)))) {
					{
					if ((LA(1)==PLUS) && (_tokenSet_2.member(LA(2)))) {
						match(PLUS);
						sign2=1;
					}
					else if ((LA(1)==MINUS) && (_tokenSet_2.member(LA(2)))) {
						match(MINUS);
						sign2=-1;
					}
					else if ((_tokenSet_2.member(LA(1))) && (_tokenSet_4.member(LA(2)))) {
					}
					else {
						throw new NoViableAltException(LT(1), getFilename());
					}
					
					}
					{
					switch ( LA(1)) {
					case PLUS:
					case MINUS:
					case INTEGER_THING:
					case DOT:
					{
						temp2=doubleThing();
						{
						switch ( LA(1)) {
						case STAR:
						{
							match(STAR);
							break;
						}
						case LITERAL_I:
						{
							break;
						}
						default:
						{
							throw new NoViableAltException(LT(1), getFilename());
						}
						}
						}
						match(LITERAL_I);
						im=sign2*temp2;
						break;
					}
					case LITERAL_I:
					{
						match(LITERAL_I);
						im=sign2*1;
						break;
					}
					default:
					{
						throw new NoViableAltException(LT(1), getFilename());
					}
					}
					}
				}
				else if ((LA(1)==COLLON||LA(1)==CLOSE_BRACE)) {
				}
				else {
					throw new NoViableAltException(LT(1), getFilename());
				}
				
				}
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			c.setValue(re, im);
		}
		catch (RecognitionException ex) {
			reportError(ex);
			consume();
			consumeUntil(_tokenSet_5);
		}
		return c;
	}
	
	private final double  doubleThing() throws RecognitionException, TokenStreamException {
		double d;
		
		Token  s = null;
		Token  s2 = null;
		Token  s3 = null;
		d=0; double e=0; String sig="";
		
		try {      // for error handling
			{
			switch ( LA(1)) {
			case PLUS:
			{
				match(PLUS);
				break;
			}
			case MINUS:
			{
				match(MINUS);
				sig="-";
				break;
			}
			case INTEGER_THING:
			case DOT:
			{
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			{
			switch ( LA(1)) {
			case INTEGER_THING:
			{
				s = LT(1);
				match(INTEGER_THING);
				d=Double.parseDouble(sig + s.getText());
				{
				if ((LA(1)==DOT) && (_tokenSet_3.member(LA(2)))) {
					match(DOT);
					{
					if ((LA(1)==INTEGER_THING) && (_tokenSet_3.member(LA(2)))) {
						s2 = LT(1);
						match(INTEGER_THING);
						d=Double.parseDouble(sig + s.getText()+ "." + s2.getText());
					}
					else if ((_tokenSet_3.member(LA(1))) && (_tokenSet_6.member(LA(2)))) {
					}
					else {
						throw new NoViableAltException(LT(1), getFilename());
					}
					
					}
				}
				else if ((_tokenSet_3.member(LA(1))) && (_tokenSet_6.member(LA(2)))) {
				}
				else {
					throw new NoViableAltException(LT(1), getFilename());
				}
				
				}
				break;
			}
			case DOT:
			{
				match(DOT);
				s3 = LT(1);
				match(INTEGER_THING);
				d=Double.parseDouble(sig + "0." + s3.getText());
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			{
			if ((LA(1)==STAR) && (LA(2)==HAT)) {
				e=exponentThing();
				d=d*Math.pow(10,e);
			}
			else if ((_tokenSet_3.member(LA(1))) && (_tokenSet_7.member(LA(2)))) {
			}
			else {
				throw new NoViableAltException(LT(1), getFilename());
			}
			
			}
		}
		catch (RecognitionException ex) {
			reportError(ex);
			consume();
			consumeUntil(_tokenSet_3);
		}
		return d;
	}
	
	private final int  exponentThing() throws RecognitionException, TokenStreamException {
		int e;
		
		Token  s = null;
		e=0; String sig="";
		
		try {      // for error handling
			match(STAR);
			match(HAT);
			{
			switch ( LA(1)) {
			case PLUS:
			{
				match(PLUS);
				break;
			}
			case MINUS:
			{
				match(MINUS);
				sig="-";
				break;
			}
			case INTEGER_THING:
			{
				break;
			}
			default:
			{
				throw new NoViableAltException(LT(1), getFilename());
			}
			}
			}
			s = LT(1);
			match(INTEGER_THING);
			e=Integer.parseInt(sig + s.getText() );
		}
		catch (RecognitionException ex) {
			reportError(ex);
			consume();
			consumeUntil(_tokenSet_3);
		}
		return e;
	}
	
	
	public static final String[] _tokenNames = {
		"<0>",
		"EOF",
		"<2>",
		"NULL_TREE_LOOKAHEAD",
		"OPEN_BRACE",
		"COLLON",
		"CLOSE_BRACE",
		"PLUS",
		"MINUS",
		"INTEGER_THING",
		"DOT",
		"STAR",
		"HAT",
		"\"I\"",
		"BACKS",
		"SLASH",
		"DDOT",
		"an identifier",
		"ID_LETTER",
		"DIGIT",
		"STRING",
		"ESC",
		"WS_"
	};
	
	private static final long[] mk_tokenSet_0() {
		long[] data = { 2L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_0 = new BitSet(mk_tokenSet_0());
	private static final long[] mk_tokenSet_1() {
		long[] data = { 98L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_1 = new BitSet(mk_tokenSet_1());
	private static final long[] mk_tokenSet_2() {
		long[] data = { 10112L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_2 = new BitSet(mk_tokenSet_2());
	private static final long[] mk_tokenSet_3() {
		long[] data = { 12256L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_3 = new BitSet(mk_tokenSet_3());
	private static final long[] mk_tokenSet_4() {
		long[] data = { 11872L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_4 = new BitSet(mk_tokenSet_4());
	private static final long[] mk_tokenSet_5() {
		long[] data = { 96L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_5 = new BitSet(mk_tokenSet_5());
	private static final long[] mk_tokenSet_6() {
		long[] data = { 16354L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_6 = new BitSet(mk_tokenSet_6());
	private static final long[] mk_tokenSet_7() {
		long[] data = { 12258L, 0L};
		return data;
	}
	public static final BitSet _tokenSet_7 = new BitSet(mk_tokenSet_7());
	
	}
